import { setSpeed } from '../src/core/time.js';
import { Runtime } from '../src/sim/runtime.js';
import { commonsSystems } from '../src/world/index.js';
import type { PrincipalId } from '../src/core/types.js';
setSpeed('instant');
const r = new Runtime({ seed: 'probe' });
const stage = commonsSystems(r.world.map)[0]!;
const p = 'p:lp01' as PrincipalId;
r.seat(p, 'lp01', stage);
r.standing.open(p);
r.runTick();
const kinds = new Map<string, number>();
for (const t of r.events.ticks()) for (const e of r.events.eventsAtTick(t)) kinds.set(e.kind, (kinds.get(e.kind) ?? 0) + 1);
console.log('after 1 tick', [...kinds]);
console.log('block', r.levyBlockFor(p, r.engine.tick));
